#!/usr/bin/env bash
# provision-compose-overrides.sh — hardware-conditional compose fragments.
#
# WHY THIS EXISTS
#   `docker-compose.yml` is one file shared by the real AWOW, the sim, and the
#   Hyper-V V3-gate VM. A `devices:` entry is NOT best-effort: if the node is
#   missing, container CREATION fails, and `docker compose up -d` reports that
#   as a failure for the whole run. Jellyfin's Quick Sync passthrough
#   (/dev/dri, the J4125's iGPU via i915) is therefore impossible to express in
#   the base file without breaking every box that has no iGPU.
#
#   So the base file carries NO devices block, and this script writes a
#   `docker-compose.override.yml` next to it when — and only when — the
#   hardware is actually there. Compose auto-loads that filename for every
#   `docker compose` invocation in the directory, so firstboot AND a later
#   manual `docker compose up -d` over SSH both pick it up with no extra flags.
#
# IDEMPOTENT + SELF-HEALING: re-running rewrites the file from scratch, and a
# box that LOSES /dev/dri (or is restored from an image onto different
# hardware) gets the stale override REMOVED rather than left to fail.
#
# Only ever writes a file it owns: the generated header is checked before an
# existing override is touched, so a hand-written override is never clobbered.
set -euo pipefail

STACK_DIR="${STACK_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
OVERRIDE="$STACK_DIR/docker-compose.override.yml"
MARKER='# GENERATED by provision-compose-overrides.sh — DO NOT EDIT'
# Overridable so the three branches below can be exercised on a box that has no
# iGPU (the dev PC, WSL, the gate VM) — production never sets it.
RENDER_NODE="${RENDER_NODE:-/dev/dri}"

log() { echo "[provision-overrides] $*"; }

# Refuse to touch an override this script did not write.
if [ -e "$OVERRIDE" ] && ! head -1 "$OVERRIDE" | grep -qF "$MARKER"; then
    log "$OVERRIDE exists and is NOT ours (no generated header) — leaving it alone."
    exit 0
fi

if [ ! -d "$RENDER_NODE" ]; then
    if [ -e "$OVERRIDE" ]; then
        rm -f "$OVERRIDE"
        log "no $RENDER_NODE on this box — removed the stale QSV override."
    else
        log "no $RENDER_NODE on this box — no override needed (Jellyfin will transcode on CPU)."
    fi
    exit 0
fi

cat > "$OVERRIDE" <<EOF
$MARKER
# Regenerated on every firstboot run from the hardware actually present.
# Delete it and re-run provision-compose-overrides.sh to refresh.
#
# $RENDER_NODE exists on this machine, so Jellyfin gets the iGPU for hardware
# transcoding (VA-API / Intel Quick Sync). Enable it in Jellyfin's own UI too:
# Dashboard -> Playback -> Hardware acceleration -> Video Acceleration API.
services:
  jellyfin:
    devices:
      - $RENDER_NODE:$RENDER_NODE
EOF

log "wrote $OVERRIDE — Jellyfin gets $RENDER_NODE ($(ls "$RENDER_NODE" | tr '\n' ' '))"
