#!/usr/bin/env bash
# restore-volumes.sh — put the hand-made service state back after a reimage.
#
# Called by firstboot step 4a-pre-5, from inside its fail-open subshell, once the
# backup drive is readable. It is a SEPARATE FILE rather than an inline loop for
# one reason: the inline version could only be tested by reimaging a box, and a
# restore path that has never been executed is how C22 happened — the caddy_data
# restore existed for months, looked correct in review, and had never once fired.
# With the loop here it takes a mock `docker` on PATH and a temp directory.
#
# THE CONTRACT, inherited whole from the step it came out of:
#   * FAIL-OPEN. Every failure leaves things exactly as they were. This can only
#     ever SAVE work; it must never be able to withhold a boot.
#   * ONLY INTO AN EMPTY VOLUME. Content already there means this is not the
#     fresh install the step is for, and the on-disk material wins.
#   * EVERY SET IS INDEPENDENT. A missing `tracker` archive must not be able to
#     cost caddy its certificates — which is exactly what the single-set shape's
#     `exit 0` on every miss would have done once there was more than one set.
#
# Usage: restore-volumes.sh SOURCE_DIR RESULT_LOG [TABLE]
#   SOURCE_DIR  a directory holding run_<ts>/ archive directories (the mounted
#               backup drive, or the read-only temporary mount firstboot makes)
#   RESULT_LOG  appended to, one line per set: `ok|skip|FAIL <set> <detail>`
#   TABLE       space-separated set:volume:service triples; defaults to
#               $HOMEHUB_RESTORE_VOLUMES, then to the built-in four
#
# Exit is always 0 unless the arguments are wrong (2). The RESULT_LOG is the
# output; the exit code deliberately carries no verdict, because a caller that
# treated "nothing to restore" as failure would be wrong on every healthy box.
set -uo pipefail

[ $# -ge 2 ] || { echo "usage: restore-volumes.sh SOURCE_DIR RESULT_LOG [TABLE]" >&2; exit 2; }
SRC="$1"; LOG="$2"; TABLE="${3:-}"
# Where a FAILED cleanup leaves its note. Outside the volume, so the service
# never sees it, and outside /run, so it survives the reboot on which the
# problem actually shows up.
FAILDIR="${HOMEHUB_RESTORE_FAILDIR:-/var/lib/homehub/restore-failed}"

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STACK_DIR="${STACK_DIR:-$(cd "$HERE/.." && pwd)}"
RESTORE_SH="${RESTORE_SH:-$STACK_DIR/backup/restore.sh}"
COMMON_SH="${COMMON_SH:-$STACK_DIR/backup/common.sh}"

# newest_run_with_set + volume_mountpoint live in the backup service's common.sh
# because firstboot's restore asks the identical questions restore.sh does, and
# two copies of "which run actually holds this set" is how one of them ends up
# quietly wrong.
# shellcheck source=../backup/common.sh
. "$COMMON_SH" 2>/dev/null || { printf 'skip - could not source %s\n' "$COMMON_SH" >>"$LOG"; exit 0; }

# WHY THESE FOUR, and why not the fifth:
#   caddy       ACME account key + certificates. The original, and the only one
#               with a rate limit behind it (C22: 122 refusals, the apex cert
#               2h40m late).
#   tracker     the household's item definitions and day logs. Ruling 5 said
#               "not needed, the traceability mirror is the off-box copy" - true,
#               but the mirror is ONE-WAY by construction: it pushes and never
#               pulls, so restoring from it is a `git clone` by hand at exactly
#               the moment nobody wants to be doing that.
#   actual      the budget file created by hand in a browser. This is C21
#               ceasing to recur once per reimage.
#   uptimekuma  the monitors, when there are any. Empty today, which is the
#               cheapest possible moment to wire it (Q2, the Owner).
#   technitium  DELIBERATELY ABSENT. Its state is DECLARATIVE - zones and records
#               are regenerated by provision-technitium.sh from the storage map
#               on every boot - so a restore recovers almost nothing while
#               carrying a real hazard: it would resurrect whatever admin
#               password the archive holds, and if that secret is ever rotated
#               the provisioner's login starts failing on a freshly imaged box.
DEFAULT_TABLE='caddy:caddy_data:caddy tracker:tracker_data:tracker actual:actual_data:actual uptimekuma:uptimekuma_data:uptime-kuma'
[ -n "$TABLE" ] || TABLE="${HOMEHUB_RESTORE_VOLUMES:-$DEFAULT_TABLE}"

# vol_exists VOL — does docker already know this volume, by either name? Asked
# BEFORE `compose create`, because the answer changes what "empty" means.
vol_exists() {
    docker volume inspect "$1" >/dev/null 2>&1 && return 0
    docker volume inspect "stack_$1" >/dev/null 2>&1 && return 0
    [ -n "$(docker volume ls -q --filter "label=com.docker.compose.volume=$1" 2>/dev/null)" ]
}

# dir_has_content DIR — 0 = has something, 1 = empty, 2 = COULD NOT TELL.
#
# NOT `[ -n "$(ls -A "$d")" ]`, which was the first cut and fails in the
# dangerous direction: if `ls` errors the substitution is empty, the directory
# reads as EMPTY, and a restore lands on top of a populated volume. Three
# outcomes, and the caller treats "could not tell" as "leave it alone".
# (Adversarial review, 2026-08-29.)
dir_has_content() {
    local d="$1" out rc
    out="$(find "$d" -mindepth 1 -maxdepth 1 -print -quit 2>/dev/null)"; rc=$?
    [ "$rc" -eq 0 ] || return 2
    [ -n "$out" ] && return 0
    return 1
}

for entry in $TABLE; do
    # SHAPE FIRST, AND WITH `case`, NOT A CHAIN OF `[ ] || [ ] && [ ]`. The first
    # cut of this validation was written as one long `||` chain ending in an
    # `&&`, and in shell those have EQUAL precedence and associate left — so the
    # trailing condition was ANDed against the whole chain and a genuinely empty
    # field could still pass. Caught by writing the test before trusting it.
    case "$entry" in
        *:*:*:*) printf 'FAIL - malformed table entry %s (too many fields; want set:volume:service)\n' "$entry" >>"$LOG"; continue ;;
        *:*:*)   ;;
        *)       printf 'FAIL - malformed table entry %s (want set:volume:service)\n' "$entry" >>"$LOG"; continue ;;
    esac
    set_name="${entry%%:*}"; rest="${entry#*:}"
    vol="${rest%%:*}"; svc="${rest#*:}"
    if [ -z "$set_name" ] || [ -z "$vol" ] || [ -z "$svc" ]; then
        # A MALFORMED ROW IS SAID OUT LOUD, not skipped in silence. This table is
        # the kind of thing someone edits in a hurry on the box; an empty field
        # would otherwise restore nothing and read as "no archive on the drive".
        printf 'FAIL - table entry %s has an empty field (want set:volume:service)\n' "$entry" >>"$LOG"
        continue
    fi

    # A PREVIOUS BOOT'S FAILED RESTORE LEFT A NOTE. Without this, a half-filled
    # volume reads as "not empty (this is not a fresh install)" on every later
    # boot — a true sentence that hides a broken volume forever.
    if [ -e "$FAILDIR/$vol" ]; then
        printf 'FAIL %s a previous restore failed and could not clean up; %s may hold a PARTIAL copy. Empty it by hand and delete %s, then reboot.\n' "$set_name" "$vol" "$FAILDIR/$vol" >>"$LOG"
        continue
    fi

    run="$(newest_run_with_set "$SRC" "$set_name")" || run=""
    if [ -z "$run" ]; then
        printf 'skip %s no archived set on the drive\n' "$set_name" >>"$LOG"
        continue
    fi

    # DID THE VOLUME EXIST BEFORE WE ASKED COMPOSE TO MAKE IT? That is the whole
    # definition of "fresh install" here, and asking it AFTERWARDS is wrong:
    # docker seeds a NEWLY created named volume from whatever the image has at
    # the mount path, so an image that ships content would make the volume
    # non-empty the instant `compose create` runs — and the restore would decline
    # on every fresh install, silently, forever. That is the C22 shape exactly,
    # and it is the finding this whole file exists to not repeat.
    # (Adversarial review, 2026-08-29.)
    if vol_exists "$vol"; then pre_existed=1; else pre_existed=0; fi

    # COMPOSE creates the volume, not us: that way it gets the project-prefixed
    # name and the labels compose looks for later, instead of a hand-built name
    # this script would have to keep in step with the project directory.
    # `create` makes the containers and their volumes without starting anything.
    if ! docker compose create "$svc" >/dev/null 2>&1; then
        printf 'skip %s compose could not create service %s\n' "$set_name" "$svc" >>"$LOG"
        continue
    fi
    vmp="$(volume_mountpoint "$vol")" || vmp=""
    if [ -z "$vmp" ] || [ ! -d "$vmp" ]; then
        printf 'skip %s volume %s has no mountpoint\n' "$set_name" "$vol" >>"$LOG"
        continue
    fi

    # ONLY INTO A FRESH VOLUME.
    if [ "$pre_existed" = 1 ]; then
        dir_has_content "$vmp"; hc=$?
        case "$hc" in
            0) printf 'skip %s volume %s already existed and is not empty (this is not a fresh install)\n' "$set_name" "$vol" >>"$LOG"; continue ;;
            2) printf 'FAIL %s could not read %s to decide whether it is empty; leaving it alone\n' "$set_name" "$vmp" >>"$LOG"; continue ;;
        esac
    else
        # The volume did not exist a moment ago, so anything in it now is IMAGE
        # SEED DATA. The archive is a full copy of a real volume of the same
        # service, so the seed is exactly what it replaces — but say so, because
        # deleting bytes is never something to do quietly.
        if dir_has_content "$vmp"; then
            printf 'note %s volume %s was created by this step and holds image seed data; clearing it before restore\n' "$set_name" "$vol" >>"$LOG"
            if ! find "$vmp" -xdev -mindepth 1 -delete 2>/dev/null; then
                printf 'FAIL %s could not clear the image seed data in %s; leaving it alone\n' "$set_name" "$vmp" >>"$LOG"
                continue
            fi
        fi
    fi

    if bash "$RESTORE_SH" --run "$run" --set "$set_name" --target "$vmp" >/dev/null 2>&1; then
        printf 'ok %s from %s -> %s\n' "$set_name" "$(basename "$run")" "$vol" >>"$LOG"
    else
        # A FAILED RESTORE LEAVES A HALF-FILLED VOLUME, and that is worse than an
        # empty one: the "only into a fresh volume" guard would decline on every
        # later boot, so the box would carry the wreckage forever and the failure
        # would present as "already restored". restore.sh verifies every file
        # byte-for-byte, so a nonzero exit means the archive did not reconstruct.
        # Throw the partial away and let the service start clean.
        #
        # `-xdev` IS LOAD-BEARING: GNU find crosses filesystem boundaries, so
        # without it a mount nested under the volume would be emptied with it.
        if find "$vmp" -xdev -mindepth 1 -delete 2>/dev/null; then
            printf 'FAIL %s restore.sh refused or failed; %s was emptied again so the next boot retries\n' "$set_name" "$vol" >>"$LOG"
        else
            # THE CLEANUP ITSELF FAILED, which is the state that used to become
            # permanent silence. Leave a note OUTSIDE the volume (so the service
            # never sees it) and outside /run (so it survives the reboot on which
            # the problem actually shows up), and read it at the top of the next
            # pass. Otherwise the next boot says "not empty, so not a fresh
            # install" — a true sentence about a broken volume.
            mkdir -p "$FAILDIR" 2>/dev/null && : >"$FAILDIR/$vol" 2>/dev/null || true
            printf 'FAIL %s restore.sh failed AND %s could not be emptied — it may hold a PARTIAL copy. Empty it by hand and delete %s.\n' "$set_name" "$vmp" "$FAILDIR/$vol" >>"$LOG"
        fi
    fi
done
exit 0
