#!/usr/bin/env bash
# setup-ai-cli.sh — create the dedicated account and install the AI CLI service.
#
# Idempotent and non-interactive, like every other setup script here. It is
# called from firstboot only when AI_CLI_ENABLED=true; on a box where the knob
# is false it does nothing at all, and nothing it would have installed exists.
#
# WHAT THIS SCRIPT IS FOR, in one line: acceptance criterion 1 of A40 —
# a DEDICATED UNPRIVILEGED ACCOUNT, never `hub`.
#
# `hub` is the box's only account with a real shell and it carries
# (ALL) NOPASSWD: ALL (stack/remote-ui/homehub-desktop-session.sh). A service
# running as `hub`, driving an agent, taking requests from other containers is
# arbitrary code execution as a passwordless-sudo user chosen by the caller.
# So: a new account, no sudo, not in `docker` (which is sudo by another door),
# and — per A40 — THIS is the account the CLIs are signed into over RDP, so the
# subscription credential lives where the service runs and nowhere else.
#
# THE ACCOUNT THIS SCRIPT CHECKS IS THE ACCOUNT SYSTEMD RUNS (cross-review V2).
# The unit used to hard-code `User=homehub-ai` while this script and the service
# validated whatever `AI_CLI_USER` said, so `AI_CLI_USER=alice` had setup create
# and certify `alice` while systemd still started `homehub-ai`. Now this script
# writes the unit's `User=`/`Group=` into a drop-in FROM THAT SAME KNOB, and the
# service asserts its own effective identity at startup — so the two cannot be
# different things, by construction rather than by discipline.
#
# The account keeps a real shell on purpose. It has to: `claude setup-token`
# is run inside an RDP session as this user, and a nologin shell would make
# that impossible. A shell is not a privilege; sudo is, and this account has
# none. The script REFUSES to proceed if the account has picked one up.
#
# Adds NO apt package: the service is Python 3 stdlib only and python3 is
# already in packages.list. The CLIs themselves are not apt packages either
# (SN-016) and are installed over SSH by the Owner, deliberately outside the
# offline closure.
#
# Usage: setup-ai-cli.sh [--check-only | --emit-dropin DIR]
# Exit 0 = converged (or disabled). 1 = failed. 2 = refused (privilege found).
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${AI_CLI_ENV_FILE:-$HERE/../.env}"
DROPIN_DIR_DEFAULT=/etc/systemd/system/homehub-ai-cli.service.d
MODE="${1:-}"

# Defaults mirror stack/.env.example; the .env wins where it sets a key.
AI_CLI_ENABLED="${AI_CLI_ENABLED:-false}"
AI_CLI_USER="${AI_CLI_USER:-homehub-ai}"
AI_CLI_BIND="${AI_CLI_BIND:-127.0.0.1}"
AI_CLI_SCRATCH_ROOT="${AI_CLI_SCRATCH_ROOT:-/var/lib/homehub-ai/scratch}"

if [ -f "$ENV_FILE" ]; then
    # Read only the keys we own, and never `source` a file that may hold
    # secrets into this shell's environment wholesale.
    for key in AI_CLI_ENABLED AI_CLI_USER AI_CLI_BIND AI_CLI_SCRATCH_ROOT; do
        value="$(grep -E "^${key}=" "$ENV_FILE" 2>/dev/null | tail -1 | cut -d= -f2- || true)"
        [ -n "$value" ] && printf -v "$key" '%s' "$value"
    done
fi

log() { printf 'setup-ai-cli: %s\n' "$*"; }
die() { printf 'setup-ai-cli: FAILED: %s\n' "$*" >&2; exit 1; }
refuse() { printf 'setup-ai-cli: REFUSED: %s\n' "$*" >&2; exit 2; }

# The unit's account, written from the SAME knob this script certifies. This is
# the whole of V2's fix on the provisioning side: there is one place the account
# name comes from, and both systemd and the service read it.
emit_dropin() {
    local dir="$1"
    mkdir -p "$dir"
    cat > "$dir/10-account.conf" <<EOF
# GENERATED by setup-ai-cli.sh from AI_CLI_USER. Do not hand-edit: the service
# asserts its own effective identity at startup and will REFUSE to run if this
# file and AI_CLI_USER disagree (cross-review V2).
[Service]
User=$AI_CLI_USER
Group=$AI_CLI_USER
EOF
    log "unit account drop-in: $dir/10-account.conf (User=Group=$AI_CLI_USER)"
}

if [ "$AI_CLI_ENABLED" != "true" ] && [ "$MODE" != "--emit-dropin" ]; then
    log "AI_CLI_ENABLED=$AI_CLI_ENABLED — nothing installed, nothing running."
    exit 0
fi

# ── Refusal 1: never `hub`, never root. ────────────────────────────────────
case "$AI_CLI_USER" in
    hub|root|"")
        refuse "AI_CLI_USER=${AI_CLI_USER:-<empty>} — this service must not run \
as an account carrying (ALL) NOPASSWD: ALL (A40, 2026-09-09)" ;;
esac

# `--emit-dropin DIR` writes only the account drop-in and stops. No root, no
# install: it exists so a test can assert that the unit's User= really is
# derived from AI_CLI_USER, rather than grepping the shipped unit and believing
# a hard-coded name.
if [ "$MODE" = "--emit-dropin" ]; then
    [ -n "${2:-}" ] || die "--emit-dropin needs a directory"
    emit_dropin "$2"
    exit 0
fi

# ── Refusal 2: the bind address, before anything is installed. ─────────────
# Delegated to the service's own resolve_bind (`--bind-check`) rather than
# re-implemented here. The reviewed version carried its own copy of the rule,
# which is how the shell and the service ended up both trusting the whole of
# 172.16.0.0/12 — a range that contains real household LANs. One fact, one home:
# a non-loopback bind must be an address a local docker bridge is CARRYING.
python3 "$HERE/ai_cli_service.py" --bind-check "$AI_CLI_BIND" >/dev/null \
    || refuse "AI_CLI_BIND=$AI_CLI_BIND is not loopback and is not an address \
any local docker bridge is carrying"

if [ "$MODE" = "--check-only" ]; then
    log "check-only: user=$AI_CLI_USER bind=$AI_CLI_BIND — both acceptable."
    exit 0
fi

[ "$(id -u)" = 0 ] || die "must run as root to create the service account"

# ── Create the account, idempotently. ──────────────────────────────────────
if id -u "$AI_CLI_USER" >/dev/null 2>&1; then
    log "account $AI_CLI_USER already exists"
else
    # A real shell (RDP sign-in needs one) and its own home, where the CLI
    # credential will land at 0600 after `claude setup-token`. NOT in sudo,
    # NOT in docker, NOT in adm.
    useradd --create-home --shell /bin/bash --comment "HomeHub AI CLI service" \
        "$AI_CLI_USER" || die "useradd $AI_CLI_USER"
    log "created $AI_CLI_USER (no sudo, no docker)"
fi
chmod 0700 "/home/$AI_CLI_USER" 2>/dev/null || true

# ── Refusal 3: the account must still be unprivileged. Re-checked EVERY run,
# because an account created without sudo can be given it later, and this is
# the thing the block is about.
groups_now="$(id -nG "$AI_CLI_USER" 2>/dev/null || true)"
for bad in sudo admin wheel root docker adm; do
    case " $groups_now " in
        *" $bad "*) refuse "$AI_CLI_USER is in group '$bad' — a dedicated \
account that was then given sudo (or docker) is not a containment" ;;
    esac
done
# The sudoers search is the service's, not a second grep: it FOLLOWS #include /
# #includedir / @include, which the reviewed shell grep did not, so a NOPASSWD
# grant one file away was invisible to it.
AI_CLI_HERE="$HERE" python3 - "$AI_CLI_USER" <<'PY' || refuse "$AI_CLI_USER is named in (or reachable from) a sudoers rule"
import sys, os
sys.path.insert(0, os.environ["AI_CLI_HERE"])
import ai_cli_service as svc
try:
    svc.assert_service_account(sys.argv[1], sudoers_lines=svc.collect_sudoers_lines())
except svc.ConfigError as exc:
    sys.stderr.write("setup-ai-cli: %s\n" % exc)
    sys.exit(1)
PY

# ── The scratch root: 0700, owned by the account, and empty at install. ────
install -d -m 0700 -o "$AI_CLI_USER" -g "$AI_CLI_USER" "$AI_CLI_SCRATCH_ROOT"
log "scratch root $AI_CLI_SCRATCH_ROOT is 0700 $AI_CLI_USER"

# ── The unit, plus the account drop-in generated from AI_CLI_USER. Installed
# and enabled, and NOT started here: starting it is a deployment step the Owner
# runs, and this script also runs on every boot.
install -m 0644 "$HERE/homehub-ai-cli.service" /etc/systemd/system/homehub-ai-cli.service
emit_dropin "$DROPIN_DIR_DEFAULT"
chmod 0644 "$DROPIN_DIR_DEFAULT/10-account.conf"
systemctl daemon-reload
systemctl enable homehub-ai-cli.service >/dev/null

# ── The configuration check, AS THE ACCOUNT THAT WILL RUN IT. Running it as
# root would certify an identity nobody serves under — the reviewed version did
# exactly that, which is why the account mismatch survived its own test. The
# service asserts its effective identity, so this only passes when the drop-in,
# the knob and the running user are one account.
runuser -u "$AI_CLI_USER" -- env \
    AI_CLI_BIND="$AI_CLI_BIND" AI_CLI_USER="$AI_CLI_USER" \
    AI_CLI_SCRATCH_ROOT="$AI_CLI_SCRATCH_ROOT" \
    python3 "$HERE/ai_cli_service.py" --check \
    || die "ai_cli_service.py --check refused as $AI_CLI_USER"

log "converged. The Owner still has to sign the CLIs in as $AI_CLI_USER over RDP"
log "(claude setup-token; the credential lands in ~$AI_CLI_USER/.claude at 0600)"
