#!/usr/bin/env bash
# vmtest/lib/common.sh — shared helpers for the WI-10.18 V3 gate scripts.
# Sourced by build-seed.sh and build-repacked-iso.sh. Not standalone.

log()  { echo "[vmtest] $*" >&2; }
die()  { echo "[vmtest] FATAL: $*" >&2; exit 1; }

require_cmd() {
    command -v "$1" >/dev/null 2>&1 || die "required command '$1' not found. $2"
}

# require_free_gb DIR GB — abort if the filesystem holding DIR has less than
# GB gigabytes free. Creates DIR first (mkdir -p) so a not-yet-existing output
# dir can still be statted.
require_free_gb() {
    local dir="$1" need_gb="$2" avail_kb avail_gb
    mkdir -p "$dir"
    avail_kb=$(df -Pk "$dir" | awk 'NR==2 {print $4}')
    avail_gb=$(( avail_kb / 1024 / 1024 ))
    if [ "$avail_gb" -lt "$need_gb" ]; then
        die "only ${avail_gb}GB free at '$dir' (need >= ${need_gb}GB). Point" \
            "OUT_DIR/ISO_CACHE_DIR at a roomier volume, e.g.:" \
            "  OUT_DIR=/mnt/d/vmtest-out bash vmtest/build-seed.sh"
    fi
    log "disk check OK: ${avail_gb}GB free at '$dir' (need >= ${need_gb}GB)"
}

# repo_root — resolve the MiniPC-Deployer repo root from this file's location
# (vmtest/lib/common.sh -> two dirs up), regardless of caller's cwd.
repo_root() {
    local here
    here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    (cd "$here/../.." && pwd)
}

# sim_banner NAME — printed at the top of every generated SIM artifact so
# nobody mistakes it for a real credential.
sim_banner() {
    cat <<EOF
# ============================================================================
# SIM / PLACEHOLDER VALUE — generated by vmtest/$1 for the local Hyper-V V3
# gate ONLY. Not a real secret, not reused anywhere, safe to discard with the
# VM. Real materialization for the physical AWOW happens later via
# SECRET_HANDOFF_PROPOSAL, once Peter ratifies it (WI-10.3, still open).
# ============================================================================
EOF
}

# render_seed_tree REPO_ROOT OUT_DIR CALLER_NAME
#
# Shared by build-seed.sh and build-repacked-iso.sh: materializes
# $OUT_DIR/iso-root/{user-data,meta-data,deploy-payload/} from the REAL
# stack/autoinstall/ + stack/.env.example with SIM values substituted, plus an
# ephemeral SSH keypair and a SIM console password under $OUT_DIR/{ssh,secrets}.
# Idempotent: reuses an existing SSH key / SIM password across calls (pass
# CLEAN=1 in the environment to force fresh ones). Never touches the stock
# Ubuntu ISO — that only happens in build-repacked-iso.sh, after this returns.
render_seed_tree() {
    local repo_root="$1" out_dir="$2" caller="$3"
    local autoinstall_src="$repo_root/stack/autoinstall"
    local stack_env_example="$repo_root/stack/.env.example"

    [ -f "$autoinstall_src/user-data" ] || die "not found: $autoinstall_src/user-data (run from a MiniPC-Deployer checkout)"
    [ -f "$stack_env_example" ] || die "not found: $stack_env_example"
    require_cmd openssl "Install with: sudo apt-get install -y openssl"
    require_cmd ssh-keygen "Install with: sudo apt-get install -y openssh-client"

    if [ "${CLEAN:-0}" -eq 1 ] && [ -d "$out_dir" ]; then
        log "CLEAN=1: wiping previous $out_dir"
        rm -rf "$out_dir"
    fi

    mkdir -p "$out_dir/ssh" "$out_dir/iso-root/deploy-payload" "$out_dir/secrets"
    chmod 700 "$out_dir/ssh" "$out_dir/secrets"

    # ── ephemeral SSH keypair (disposable, VM-test only) ─────────────────────
    local ssh_key="$out_dir/ssh/awow-vmtest-ed25519"
    if [ ! -f "$ssh_key" ]; then
        log "generating ephemeral SSH keypair for the test VM (not reused anywhere else)"
        ssh-keygen -q -t ed25519 -N "" -C "awow-vmtest (disposable, WI-10.18 V3 gate)" -f "$ssh_key"
    else
        log "reusing existing ephemeral SSH keypair at $ssh_key (pass --clean to regenerate)"
    fi
    SSH_KEY="$ssh_key"   # exported for the caller
    local ssh_pubkey; ssh_pubkey="$(cat "$ssh_key.pub")"

    # ── SIM secrets: console password + Technitium admin password + oauth2-proxy
    #    cookie secret, all generated ONCE and reused across re-runs (pass
    #    CLEAN=1 to force fresh ones) so build-seed.sh / build-repacked-iso.sh
    #    can be re-run idempotently without silently drifting secrets between
    #    the seed and a previously-built ISO. ─────────────────────────────────
    local creds_file="$out_dir/secrets/creds.env"
    CREDS_FILE="$creds_file"   # exported for the caller
    local sim_password sim_password_hash cookie_secret technitium_pw
    if [ ! -f "$creds_file" ]; then
        sim_password="vmtest-$(openssl rand -hex 6)"
        sim_password_hash="$(openssl passwd -6 "$sim_password")"
        cookie_secret="$(openssl rand -base64 32 | tr -- '+/' '-_')"
        technitium_pw="$(openssl rand -base64 18)"
        {
            sim_banner "$caller"
            echo "SIM_CONSOLE_PASSWORD=$sim_password"
            echo "SIM_CONSOLE_PASSWORD_HASH=$sim_password_hash"
            echo "TECHNITIUM_ADMIN_PASSWORD=$technitium_pw"
            echo "OAUTH2_PROXY_COOKIE_SECRET=$cookie_secret"
        } > "$creds_file"
        chmod 600 "$creds_file"
    else
        log "reusing existing SIM secrets at $creds_file (pass --clean to regenerate)"
        # Extract by grep, NOT by sourcing: the password hash contains
        # '$N$...' crypt syntax which bash would try to expand as positional
        # parameters if this file were sourced under `set -u`.
        sim_password="$(grep '^SIM_CONSOLE_PASSWORD=' "$creds_file" | cut -d= -f2-)"
        sim_password_hash="$(grep '^SIM_CONSOLE_PASSWORD_HASH=' "$creds_file" | cut -d= -f2-)"
        technitium_pw="$(grep '^TECHNITIUM_ADMIN_PASSWORD=' "$creds_file" | cut -d= -f2-)"
        cookie_secret="$(grep '^OAUTH2_PROXY_COOKIE_SECRET=' "$creds_file" | cut -d= -f2-)"
    fi

    # ── render user-data: SSH placeholder + password + hostname ──────────────
    # operator user: SSH key-only in production (WI-10.12); for this disposable
    # VM we ALSO allow password login at the console for convenience — never
    # do this on the real AWOW (stack/README.md's runbook keeps allow-pw:false).
    local user_data_out="$out_dir/iso-root/user-data"
    sed \
        -e "s#- \"ssh-ed25519 AAAA_REPLACE_WITH_YOUR_PUBLIC_KEY you@host\"#- \"$ssh_pubkey\"#" \
        -e 's/allow-pw: false/allow-pw: true   # VMTEST ONLY - production keeps this false (key-only)/' \
        -e "s|password: \"!\"|password: \"$sim_password_hash\"   # VMTEST ONLY sim password, see vmtest/.out/secrets/creds.env|" \
        -e 's/hostname: awow-core/hostname: awow-vmtest/' \
        -e 's/realname: "AWOW Core Operator"/realname: "AWOW VM Test Operator"/' \
        "$autoinstall_src/user-data" > "$user_data_out"
    grep -q "REPLACE_WITH_YOUR_PUBLIC_KEY" "$user_data_out" && die "SSH placeholder substitution failed"

    # ── meta-data: fresh instance-id per build, vmtest hostname ──────────────
    sed \
        -e "s/instance-id: awow-core-001/instance-id: awow-vmtest-$(date +%Y%m%d%H%M%S)/" \
        -e 's/local-hostname: awow-core/local-hostname: awow-vmtest/' \
        "$autoinstall_src/meta-data" > "$out_dir/iso-root/meta-data"

    # ── deploy-payload/ = a copy of the whole repo (late-commands expects
    #    deploy-payload/stack/... at its root) ────────────────────────────────
    local payload_dir="$out_dir/iso-root/deploy-payload"
    rm -rf "$payload_dir"
    mkdir -p "$payload_dir"
    log "copying repo into deploy-payload/ (excludes .git, vmtest/.out)"
    ( cd "$repo_root" && tar -c --exclude=.git --exclude=vmtest/.out . ) | ( cd "$payload_dir" && tar -x )

    # ── SIM .env — syntactically-valid, internally-consistent placeholders so
    #    `docker compose up -d` can actually run. See vmtest/README.md "what
    #    success looks like" for which services this does/doesn't get to
    #    healthy (the tracker image is a KNOWN gap, documented there). ────────
    local sim_env="$payload_dir/stack/.env"
    local basicauth_hash_actual="REPLACE_WITH_caddy_hash-password_OUTPUT"
    local basicauth_hash_dns="REPLACE_WITH_caddy_hash-password_OUTPUT"
    if command -v docker >/dev/null 2>&1; then
        log "generating real Caddy bcrypt basic_auth hashes via docker (SIM passwords, not secrets)"
        basicauth_hash_actual="$(docker run --rm caddy:2-alpine caddy hash-password --plaintext "sim-actual-$(openssl rand -hex 4)" 2>/dev/null || echo "$basicauth_hash_actual")"
        basicauth_hash_dns="$(docker run --rm caddy:2-alpine caddy hash-password --plaintext "sim-dns-$(openssl rand -hex 4)" 2>/dev/null || echo "$basicauth_hash_dns")"
    else
        log "WARNING: docker not found in WSL - basic_auth hashes left as REPLACE_WITH placeholders." \
            "Caddy will still start, but basic_auth logins won't work until you run:" \
            "docker run --rm caddy:2-alpine caddy hash-password --plaintext 'yourpass'"
    fi

    cp "$stack_env_example" "$sim_env"
    # NOTE: the SIM .env pins the SAME image tags as .env.example (this is a copy
    # of it), so the images baked by export-images.sh match what compose asks for.
    # NOTE: delimiter is '|' throughout — several replacements carry an inline
    # NOTE: delimiter is '|' throughout — several replacements carry an inline
    # '#' YAML/dotenv comment, which would otherwise prematurely terminate a
    # '#'-delimited sed expression.
    sed -i \
        -e "s|^DOMAIN=.*|DOMAIN=vmtest.sim.invalid|" \
        -e "s|^LAN_IP=.*|LAN_IP=0.0.0.0   # VMTEST: unknown until Hyper-V NAT assigns a DHCP lease; 0.0.0.0 = bind all, harmless in a NAT'd test VM. Production MUST set the real LAN reservation IP.|" \
        -e "s|^MAIN_BOX_IP=.*|MAIN_BOX_IP=|" \
        -e "s|^DNS_HOSTNAME=.*|DNS_HOSTNAME=dns.vmtest.sim.invalid|" \
        -e "s|^ACME_EMAIL=.*|ACME_EMAIL=vmtest@example.invalid   # no real ACME in a VM, see vmtest/README.md|" \
        -e "s|^ACTUAL_BASICAUTH_HASH=.*|ACTUAL_BASICAUTH_HASH=$basicauth_hash_actual|" \
        -e "s|^DNS_BASICAUTH_HASH=.*|DNS_BASICAUTH_HASH=$basicauth_hash_dns|" \
        -e "s|^OAUTH2_PROXY_CLIENT_ID=.*|OAUTH2_PROXY_CLIENT_ID=sim-client-id.apps.googleusercontent.com|" \
        -e "s|^OAUTH2_PROXY_CLIENT_SECRET=.*|OAUTH2_PROXY_CLIENT_SECRET=sim-client-secret-not-real|" \
        -e "s|^OAUTH2_PROXY_COOKIE_SECRET=.*|OAUTH2_PROXY_COOKIE_SECRET=$cookie_secret|" \
        -e "s|^OAUTH2_PROXY_ALLOWED_EMAILS=.*|OAUTH2_PROXY_ALLOWED_EMAILS=simuser@example.invalid|" \
        -e "s|^TECHNITIUM_ADMIN_PASSWORD=.*|TECHNITIUM_ADMIN_PASSWORD=$technitium_pw|" \
        -e "s|^CLOUDFLARE_ZONE_ID=.*|CLOUDFLARE_ZONE_ID=sim-zone-id-not-real|" \
        -e "s|^CLOUDFLARE_API_TOKEN=.*|CLOUDFLARE_API_TOKEN=sim-token-not-real   # ddns WILL fail auth in the VM - expected, no healthcheck gates it|" \
        "$sim_env"
}

# stage_images_into_payload OUT_DIR IMAGES_OUT
#
# Q10.9 B+ ALL-IMAGES: copy the docker-save image tars produced by
# vmtest/export-images.sh into the deploy-payload's images/ subdir, so they ride
# onto BOTH ISO paths and land at /opt/awow-core/images on the target, where
# firstboot.sh docker-loads them before `docker compose up -d`. The tars live in
# vmtest/.out/images by default — which render_seed_tree's repo copy EXCLUDES
# (via --exclude=vmtest/.out) — so this is the one place they enter the payload.
#
# GRACEFUL: if the staging dir is empty/missing, warn LOUDLY and still build the
# seed — the box will fall back to pulling at first boot (firstboot.sh handles
# that path), except naglight:local which has no registry and would then fail.
stage_images_into_payload() {
    local out_dir="$1" images_out="$2"
    local dest="$out_dir/iso-root/deploy-payload/images"
    mkdir -p "$dest"

    local had_nullglob=0
    shopt -q nullglob && had_nullglob=1
    shopt -s nullglob
    local tars=("$images_out"/*.tar "$images_out"/*.tar.zst)

    if [ "${#tars[@]}" -eq 0 ]; then
        [ "$had_nullglob" -eq 1 ] || shopt -u nullglob
        log "WARNING: no image tars found in $images_out — the payload will carry NO"
        log "  container images. Run  bash vmtest/export-images.sh  first to bake the"
        log "  Q10.9 B+ all-images payload, then rebuild. Without it the VM falls back"
        log "  to pulling at first boot (needs internet; naglight:local has no registry"
        log "  home and will fail to start)."
        return 0
    fi

    log "staging ${#tars[@]} image tar(s) into deploy-payload/images/ (Q10.9 B+ ALL-IMAGES)"
    local total=0 t
    for t in "${tars[@]}"; do
        # hardlink when the filesystem allows (saves ~1GB of C: — OI-6); else copy.
        cp -l "$t" "$dest/" 2>/dev/null || cp -f "$t" "$dest/"
        total=$(( total + $(stat -c%s "$t") ))
    done
    [ -f "$images_out/images.manifest.tsv" ] && cp -f "$images_out/images.manifest.tsv" "$dest/"
    [ "$had_nullglob" -eq 1 ] || shopt -u nullglob

    log "deploy-payload/images/ = $(( total / 1024 / 1024 )) MB across ${#tars[@]} tar(s)"
    log "  -> lands at /opt/awow-core/images on the target; firstboot.sh docker-loads it."
}
