#!/usr/bin/env bash
# Build the offline, hash-pinned ProjectM preset payload that the panel installs
# (plan item Q). Same contract as build-sensor-wheelhouse.sh: the LOCK is
# committed, the files are not, and a run without --refresh either reproduces
# the locked bytes exactly or fails.
#
#   From WSL Ubuntu (the only WSL distro here with real Docker):
#     bash stack/autoinstall/wall/build-projectm-presets.sh
#   From Windows:
#     wsl -d Ubuntu -- bash /mnt/c/Projects/MiniPC-Deployer/stack/autoinstall/wall/build-projectm-presets.sh
#
# --refresh fetches the upstream pack at PRESET_REPO/PRESET_COMMIT, copies the
# files named in presets.select, and REWRITES presets.lock. That is the only
# mode that can change what a panel installs, and its output must be reviewed --
# including its licence position, which is an Owner ruling and is NOT settled
# (see projectm-presets/README.md).
set -euo pipefail

fail() { echo "[projectm-presets] $*" >&2; exit 1; }
note() { echo "[projectm-presets] $*"; }

here=$(cd "$(dirname "$0")" && pwd)
payload="$here/projectm-presets"
lock="$payload/presets.lock"
select_list="$payload/presets.select"
out=${PROJECTM_PRESET_OUT:-"$here/../../../.out-wall/projectm-presets"}

PRESET_REPO=${PRESET_REPO:-}
PRESET_COMMIT=${PRESET_COMMIT:-}

refresh=0
[ "${1:-}" = "--refresh" ] && refresh=1

[ -f "$lock" ] || fail "no lock at $lock"

# ---- reproduce ------------------------------------------------------------
if [ "$refresh" -eq 0 ]; then
    entries=$(grep -v '^[[:space:]]*#' "$lock" | grep -v '^[[:space:]]*$' || true)
    if [ -z "$entries" ]; then
        note "the lock is empty; nothing to build."
        note "That is the current, deliberate state: no preset set has been chosen"
        note "because the upstream packs carry no licence. See projectm-presets/README.md."
        exit 0
    fi
    mkdir -p "$out"
    missing=0
    # FIXED-WIDTH PARSE, BECAUSE MILKDROP FILENAMES ARE FULL OF SPACES.
    #
    # This was `read -r sha rel _`, which splits on IFS -- so a real preset path
    # like `! Transition/Fast transition to black ... .milk` parsed as rel="!"
    # and the whole reproduce path reported every one of 9795 files missing.
    # It was never noticed because the lock was empty by design until the Owner
    # ruled the pack in on 2026-09-18; the first non-empty lock broke it
    # immediately, on every line.
    #
    # A sha256 is exactly 64 hex characters and the separator is exactly two
    # spaces, so the split is positional and cannot be confused by anything a
    # filename contains -- spaces, `$`, `!`, `===`, quotes or a trailing dot.
    while IFS= read -r line; do
        [ -n "$line" ] || continue
        sha=${line:0:64}
        rel=${line:66}
        [ -n "$rel" ] || fail "malformed lock line: $line"
        if [ ! -f "$out/$rel" ]; then note "missing: $rel"; missing=1; continue; fi
        actual=$(sha256sum "$out/$rel" | cut -d' ' -f1)
        [ "$actual" = "$sha" ] || fail "hash mismatch for $rel"
    done <<< "$entries"
    [ "$missing" -eq 0 ] || fail "run --refresh on a networked machine first"
    note "every locked preset is present and matches."
    exit 0
fi

# ---- refresh --------------------------------------------------------------
[ -n "$PRESET_REPO" ] || fail "--refresh needs PRESET_REPO=<git url>"
[ -n "$PRESET_COMMIT" ] || fail "--refresh needs PRESET_COMMIT=<full sha>"
[ -f "$select_list" ] || fail "--refresh needs $select_list (one preset path per line)"

rm -rf "$out"; mkdir -p "$out"
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
git -C "$work" init -q .
git -C "$work" remote add origin "$PRESET_REPO"
git -C "$work" fetch -q --depth 1 origin "$PRESET_COMMIT"
git -C "$work" checkout -q FETCH_HEAD

: > "$lock.new"
{
    echo "# ProjectM preset lock — plan item Q. Generated by build-projectm-presets.sh."
    echo "# Upstream: $PRESET_REPO@$PRESET_COMMIT"
    echo "# FORMAT: <sha256>  <relative path>        (exactly two spaces; the path"
    echo "#          runs to end of line and MAY CONTAIN SPACES -- most do.)"
    echo "#"
    echo "# The upstream repo and commit are recorded ONCE, above, and not on"
    echo "# every line. Repeating them per entry cost 1.2 MB of the 2.4 MB this"
    echo "# file first came out as, and -- because a sha256 is a fixed 64"
    echo "# characters and the path runs to end of line -- a trailing third field"
    echo "# would have to be parsed back OFF the path, which is the exact class"
    echo "# of bug that made the reproduce path report all 9795 presets missing."
} >> "$lock.new"
count=0
# IFS= and -r: a selected path may contain spaces, and a bare `read` would strip
# leading and trailing ones.
while IFS= read -r rel; do
    case "$rel" in ''|'#'*) continue;; esac
    [ -f "$work/$rel" ] || fail "selected preset not in the pack: $rel"
    mkdir -p "$out/$(dirname "$rel")"
    cp "$work/$rel" "$out/$rel"
    printf '%s  %s\n' "$(sha256sum "$out/$rel" | cut -d' ' -f1)" "$rel" >> "$lock.new"
    count=$((count + 1))
done < "$select_list"
mv "$lock.new" "$lock"
note "locked $count preset(s) into $lock"
note "REVIEW the lock and the licence position before committing it."
