#!/usr/bin/env python3
"""Turn a directory of downloaded wheels into a hash-pinned requirements.lock.

Build-host only (it runs inside the wheelhouse build container); the panel never
executes this. Emitted format is what pip accepts under --require-hashes:

    name==version \\
        --hash=sha256:<64 hex>

One entry per distribution, sorted, with the wheel filename recorded in a
comment so a reviewer can see the platform tag that was selected without
listing the directory.
"""
from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path


def wheel_fields(path: Path) -> tuple[str, str]:
    parts = path.name[: -len(".whl")].split("-")
    if len(parts) < 5:
        raise SystemExit(f"not a wheel filename: {path.name}")
    return parts[0].replace("_", "-"), parts[1]


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        raise SystemExit("usage: write-lock.py WHEELHOUSE_DIR LOCK_PATH")
    wheelhouse, lock_path = Path(argv[1]), Path(argv[2])
    wheels = sorted(wheelhouse.glob("*.whl"), key=lambda p: p.name.lower())
    if not wheels:
        raise SystemExit("no wheels to lock; the download produced nothing")
    sdists = sorted(wheelhouse.glob("*.tar.gz"))
    if sdists:
        raise SystemExit("source distributions present: " + ", ".join(p.name for p in sdists))

    entries: dict[str, tuple[str, str, str]] = {}
    for wheel in wheels:
        name, version = wheel_fields(wheel)
        key = re.sub(r"[-_.]+", "-", name).lower()
        if key in entries and entries[key][0] != version:
            raise SystemExit(f"two versions of {name} were downloaded; resolve before locking")
        entries.setdefault(key, (version, name, wheel.name))

    lines = [
        "# Generated by build-sensor-wheelhouse.sh --refresh. Do not hand-edit.",
        "# Target: Ubuntu 24.04 noble / CPython 3.12 / x86-64 (the wall panel).",
        "# Installed offline by install-wall-capabilities.sh with",
        "#   pip install --no-index --only-binary=:all: --require-hashes --find-links <wheelhouse>",
        "",
    ]
    for key in sorted(entries):
        version, name, filename = entries[key]
        digest = sha256(wheelhouse / filename)
        lines.append(f"# {filename}")
        lines.append(f"{name}=={version} \\")
        lines.append(f"    --hash=sha256:{digest}")
    lock_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[write-lock] wrote {lock_path} with {len(entries)} pinned distributions")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
